<a href="https://colab.research.google.com/github/daju2358/Pytorch-Tu/blob/main/Tensors_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Lists

In [2]:
my_list = [[1,2,3,4,5],[6,7,8,9,10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

numpy array


In [4]:
import numpy as np
np1=np.random.rand(3,4)
np1.dtype

dtype('float64')

tensors

In [9]:
import torch

tensor_2d=torch.randn(3,4)
tensor_2d

tensor([[-0.3323,  0.4876,  1.2599, -0.7685],
        [-0.0171,  2.4940, -0.0913, -0.7337],
        [ 0.3591,  0.4043,  1.5445,  0.3232]])

In [11]:
tensor_3d = torch.randn(3,4,5)
tensor_3d

tensor([[[ 1.4797,  2.2606, -0.4959, -0.3306, -0.2140],
         [ 1.6159,  1.0720,  1.3855, -0.6223, -0.0789],
         [-0.0642, -1.3238, -1.2418, -1.2028,  0.6072],
         [-0.1166,  1.0588,  0.7009, -0.6999,  0.8329]],

        [[ 0.6420,  0.3067, -0.1203,  0.8802, -0.3364],
         [-0.4517,  0.8481,  0.2041, -0.2143,  1.0127],
         [ 0.1305,  0.5194, -1.1390,  0.6166, -0.3804],
         [-1.8554,  1.2354,  2.5795,  0.6427, -0.4170]],

        [[-0.2655,  1.8020,  0.4756, -0.3110, -0.4609],
         [-1.8121,  0.1682, -0.2142,  0.7072,  0.7997],
         [ 2.7109,  0.8664,  1.3028,  1.6210, -0.1332],
         [-0.6281,  1.7009, -1.2891,  0.1523, -0.0922]]])

In [7]:
import torch
my_torch = torch.arange(10)
my_torch
mt2 = my_torch.reshape(5,-1)
mt2


tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [13]:
#create tensor out of numpy array
my_tensor= torch.tensor(np1)
my_tensor

tensor([[0.6819, 0.2351, 0.0338, 0.8357],
        [0.7696, 0.4682, 0.5944, 0.9645],
        [0.3273, 0.0670, 0.7605, 0.6032]], dtype=torch.float64)

In [11]:
my_torch3 = torch.arange(30)
m=my_torch3.reshape(3,-1)
my_torch3
m.view(2,15)

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [17]:
#difference between shape and view
mt5=torch.arange(10)
mt5.reshape(2,5)
mt5[1]=1414
mt5.reshape(5,2)

tensor([[   0, 1414],
        [   2,    3],
        [   4,    5],
        [   6,    7],
        [   8,    9]])

In [26]:
#grab slice
tf8=mt5.reshape(5,2)
tf8[:,1]
tf8[1,:]

tensor([2, 3])

In [28]:
tensor_a=torch.tensor([1,2,3,4])
tensor_b=torch.tensor([5,6,7,8])
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [29]:
torch.add(tensor_a,tensor_b)

tensor([ 6,  8, 10, 12])

In [30]:
tensor_b-tensor_a

tensor([4, 4, 4, 4])

In [31]:
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [32]:
tensor_b/tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [33]:
#remainder modulus
tensor_b%tensor_a

tensor([0, 0, 1, 0])

In [34]:
#remainder longhand
torch.remainder(tensor_b,tensor_a)

tensor([0, 0, 1, 0])

In [35]:
torch.pow(tensor_a,tensor_b)

tensor([    1,    64,  2187, 65536])

In [39]:
tensor_a+=tensor_b
tensor_a
#儲存變動的過程

tensor([16, 20, 24, 28])